let nome="Esther";
console.log(nome);
console.log(`O meu nome é ${nome}`);
let laranjas = 5;
console.log(laranjas * laranjas);
nome= "Olivia";
console.log(nome);
laranja=83284;
console.log(laranja);
laranja = "Laranja";
console.log(laranja);